### ISSUE TITLE
Running the solution results in System.ArgumentOutOfRangeException - 

### ISSUE THREAD

**Issue by carlpr** [careercup/CtCI-6th-Edition-CSharp#12]
When I run the project for the first time, I get the following error.  

System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
  Source=System.Console
  StackTrace:
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at ctci.Library.BTreePrinter.Print(String s, Int32 top, Int32 left, Int32 right) in C:\Repos\CrackingCodingInterview\ctci.Library\BTreePrinter.cs:line 93
   at ctci.Library.BTreePrinter.Print(NodeInfo item, Int32 top) in C:\Repos\CrackingCodingInterview\ctci.Library\BTreePrinter.cs:line 76
   at ctci.Library.BTreePrinter.Print(TreeNode root, Int32 topMargin, Int32 leftMargin) in C:\Repos\CrackingCodingInterview\ctci.Library\BTreePrinter.cs:line 54
   at Chapter04.Q4_09_BST_Sequence.Run() in C:\Repos\CrackingCodingInterview\Ch 04. Trees\Q4 09 BST Sequence.cs:line 20
   at ctci.Program.Main(String[] args) in C:\Repos\CrackingCodingInterview\ctci\Program.cs:line 101

**Comment by carlpr** [comment]
II change the console window Screen Buffer Size property to a value of 420, then I don't hit this error.  :)
